-- Insert de produtos:
INSERT INTO produto (nome, categoria, preco) 
VALUES

('Atmos SolarPhone S1', 'Celulares Solares', 1399.90),
('LuminaCell X Pro Solar', 'Celulares Solares', 1750.00),
('TerraMobile E-Force One', 'Celulares Solares', 1199.50),
('Veridian SunCore Z5', 'Celulares Solares', 1970.00),
('Helios SmartTalk G6 Solar', 'Celulares Solares', 2899.99),
('NovaSpark Solarion', 'Celulares Solares', 950.00),
('AuraGlo SolarMax Phablet', 'Celulares Solares', 2250.75),
('EmberTech SolarFlare', 'Celulares Solares', 1550.00),
('Solstice Comm Phone S2', 'Celulares Solares', 2450.00),
('PhotonLink SolarWave', 'Celulares Solares', 1650.25),
('Voltaic Spark Mini Charger', 'Carregadores Solares Portáteis', 199.90),
('SunHarbor PowerBank Solar 10000mAh', 'Carregadores Solares Portáteis', 270.00),
('TerraFold Solar Charger 15W', 'Carregadores Solares Portáteis', 340.50),
('EcoFlow SolarPouch Lite', 'Carregadores Solares Portáteis', 160.00),
('HelioBoost GoFlex Pro 20W', 'Carregadores Solares Portáteis', 499.99),
('NovaCharge SolarMat Slim', 'Carregadores Solares Portáteis', 230.00),
('AuraVolt Trekker Max 20000mAh', 'Carregadores Solares Portáteis', 580.75),
('EmberLink SolarPanel Plus', 'Carregadores Solares Portáteis', 470.00),
('Solstice PowerLeaf Compact', 'Carregadores Solares Portáteis', 220.00),
('PhotonX Expedition Charger 25W', 'Carregadores Solares Portáteis', 649.25),
('Lumina Jardim SolarSense Post', 'Luminárias Solares Externas', 279.90),
('EcoPath SolarFlare Wall Light', 'Luminárias Solares Externas', 130.00),
('TerraGlo Solar Spotlight Pro', 'Luminárias Solares Externas', 240.50),
('VeridianGlow Solar Pebble Light', 'Luminárias Solares Externas', 195.00),
('HelioNight Solar Lantern Classic', 'Luminárias Solares Externas', 160.99),
('NovaLux Solar Security Lamp', 'Luminárias Solares Externas', 280.00),
('AuraBeam Solar String Lights', 'Luminárias Solares Externas', 180.75),
('EmberBright Solar Deck Light', 'Luminárias Solares Externas', 310.00),
('SolsticeGlow Solar Gate Lamp', 'Luminárias Solares Externas', 350.00),
('PhotonGuard Solar Area Light', 'Luminárias Solares Externas', 499.25),
('UrbanVolt SolarCommuter Backpack', 'Mochilas com Placa Solar', 449.90),
('TerraTrek SolarHiker Pro 30L', 'Mochilas com Placa Solar', 520.00),
('EcoCharge Daypack Solar', 'Mochilas com Placa Solar', 380.50),
('VeridianGo SolarTech Rucksack', 'Mochilas com Placa Solar', 410.00),
('HelioCarry Adventure Solar', 'Mochilas com Placa Solar', 699.99),
('NovaRoam SolarExplorer Backpack', 'Mochilas com Placa Solar', 550.00),
('AuraPace SolarActive Pack', 'Mochilas com Placa Solar', 490.75),
('EmberJourney SolarTraveler', 'Mochilas com Placa Solar', 750.00),
('SolsticeHiker SolarCharge 25L', 'Mochilas com Placa Solar', 480.00),
('PhotonHaul SolarBusiness Bag', 'Mochilas com Placa Solar', 820.25),
('EcoPower Nomad Kit Solar 30W', 'Kits de Energia Solar Pequena Escala', 650.90),
('SunGen Portable SolarStation 50W', 'Kits de Energia Solar Pequena Escala', 980.00),
('TerraKit SolarCamp Plus', 'Kits de Energia Solar Pequena Escala', 720.50),
('VeridianHome MicroGrid Kit 100W', 'Kits de Energia Solar Pequena Escala', 1850.00),
('HelioSource Off-Grid Essential', 'Kits de Energia Solar Pequena Escala', 590.99),
('NovaGrid PicoSolar Home System', 'Kits de Energia Solar Pequena Escala', 480.00),
('AuraEnergy TinySolar Kit 60W', 'Kits de Energia Solar Pequena Escala', 1350.75),
('EmberPower MobileStation 120W', 'Kits de Energia Solar Pequena Escala', 2500.00),
('SolsticeCamp PowerUnit Solar 40W', 'Kits de Energia Solar Pequena Escala', 980.00),
('PhotonPower Basic Kit 20W', 'Kits de Energia Solar Pequena Escala', 390.25);

-- Insert dos clientes
INSERT INTO clientes (nome, sobrenome, cpf, email) 
VALUES

('Ana', 'Silva', '10100100101', 'ana.silva@emailficticio.com.br'),
('Bruno', 'Costa', '10100100102', 'bruno.costa@emailficticio.com.br'),
('Carla', 'Oliveira', '10100100103', 'carla.oliveira@emailficticio.com.br'),
('Daniel', 'Almeida', '10100100104', 'daniel.almeida@emailficticio.com.br'),
('Eduarda', 'Ferreira', '10100100105', 'eduarda.ferreira@emailficticio.com.br'),
('Felipe', 'Santos', '10100100106', 'felipe.santos@emailficticio.com.br'),
('Gabriela', 'Pereira', '10100100107', 'gabriela.pereira@emailficticio.com.br'),
('Hugo', 'Rodrigues', '10100100108', 'hugo.rodrigues@emailficticio.com.br'),
('Isabela', 'Lima', '10100100109', 'isabela.lima@emailficticio.com.br'),
('João', 'Mendes', '10100100110', 'joao.mendes@emailficticio.com.br'),
('Laura', 'Gomes', '10100100111', 'laura.gomes@emailficticio.com.br'),
('Lucas', 'Martins', '10100100112', 'lucas.martins@emailficticio.com.br'),
('Mariana', 'Barbosa', '10100100113', 'mariana.barbosa@emailficticio.com.br'),
('Nicolas', 'Ribeiro', '10100100114', 'nicolas.ribeiro@emailficticio.com.br'),
('Olivia', 'Carvalho', '10100100115', 'olivia.carvalho@emailficticio.com.br'),
('Pedro', 'Azevedo', '10100100116', 'pedro.azevedo@emailficticio.com.br'),
('Sofia', 'Dias', '10100100117', 'sofia.dias@emailficticio.com.br'),
('Thiago', 'Nunes', '10100100118', 'thiago.nunes@emailficticio.com.br'),
('Valentina', 'Sousa', '10100100119', 'valentina.sousa@emailficticio.com.br'),
('Enzo', 'Lopes', '10100100120', 'enzo.lopes@emailficticio.com.br');